import type { ProjectCopyTable } from "@/lib/projectCopy";

/** Fictional browser workflow; every visible state is translated with the rest of the archive. */
export const videoMateCopy = {
  "VideoMate": ["VideoMate", "VideoMate"],
  "The recovery desk": ["视频修复工作台", "影片修復工作臺"],
  "Synthetic collection · offline simulation": ["合成样本集 · 离线模拟", "合成樣本集 · 離線模擬"],
  "Follow an invented mixed folder through VideoMate's inspect, repair and migrate decisions. The browser models technical outcomes; it does not open or process media.": ["用虚构的混合文件夹，了解 VideoMate 如何检查、修复和迁移文件。浏览器只模拟技术结果，不会打开或处理媒体。", "透過虛構的混合資料夾，瞭解 VideoMate 如何檢查、修復與遷移檔案。瀏覽器只模擬技術結果，不會開啟或處理媒體。"],
  "Select an item, switch the workflow or GPU route, then run the sample job. Compare what is published and what is held back.": ["选择一个文件，切换工作流程或 GPU 路径，再运行样本任务，比较哪些结果可交付、哪些需要暂缓。", "選擇一個檔案，切換工作流程或 GPU 路徑，再執行範例工作，比較哪些結果可交付、哪些需要暫緩。"],
  "Every candidate needs independent verification. An absent source segment stays absent, and originals are never changed.": ["每个候选结果都需要独立验证。源文件中缺失的片段仍然缺失，原始文件始终不变。", "每個候選結果都需要獨立驗證。來源檔案中缺失的片段仍然缺失，原始檔案始終不變。"],
  "5 fictional items · no uploads · no FFmpeg process": ["5 个虚构文件 · 无上传 · 不运行 FFmpeg", "5 個虛構檔案 · 無上傳 · 不執行 FFmpeg"],
  "Originals always untouched": ["原始文件始终不变", "原始檔案始終不變"],
  "OFFLINE VIDEO REPAIR": ["离线视频修复", "離線影片修復"],
  "What happens to a damaged file?": ["受损文件会怎样处理？", "受損檔案會如何處理？"],
  "Pick one of five invented files. See what VideoMate would copy, repair, re-encode or hold back.": ["从五个虚构文件中选一个，看看 VideoMate 会复制、修复、重新编码还是暂缓处理。", "從五個虛構檔案中選一個，看看 VideoMate 會複製、修復、重新編碼還是暫緩處理。"],
  "DEMO MODE": ["演示模式", "示範模式"],
  "100% synthetic": ["100% 合成数据", "100% 合成資料"],
  "No files leave or enter this page.": ["此页面不会上传或下载任何文件。", "此頁面不會上傳或下載任何檔案。"],
  "Choose a VideoMate workflow": ["选择 VideoMate 工作流程", "選擇 VideoMate 工作流程"],
  "Inspect": ["检查", "檢查"],
  "Repair": ["修复", "修復"],
  "Migrate": ["迁移", "遷移"],
  "Find what is readable": ["找出可读取的内容", "找出可讀取的內容"],
  "Recover a verified copy": ["恢复经过验证的副本", "復原經過驗證的副本"],
  "Build a new collection": ["构建新的文件集合", "建立新的檔案集合"],
  "01 / SOURCE": ["01 / 来源", "01 / 來源"],
  "Synthetic collection": ["合成样本集", "合成樣本集"],
  "05 ITEMS": ["05 个文件", "05 個檔案"],
  "Choose a sample to inspect its technical evidence. The names and findings are invented.": ["选一个样本，查看它的技术检查结果。文件名和检查结果均为虚构。", "選一個範例，查看技術檢查結果。檔名和檢查結果均為虛構。"],
  "Item": ["文件", "檔案"],
  "01 · Harbour lights": ["01 · 港湾灯光", "01 · 港灣燈光"],
  "02 · Broken index": ["02 · 损坏的索引", "02 · 損壞的索引"],
  "03 · Interrupted frames": ["03 · 中断的画面", "03 · 中斷的畫面"],
  "04 · Missing tail": ["04 · 缺失的尾段", "04 · 缺失的尾段"],
  "05 · Field notes": ["05 · 现场笔记", "05 · 現場筆記"],
  "MP4 · H.264 / AAC": ["MP4 · H.264 / AAC", "MP4 · H.264 / AAC"],
  "MOV · H.264 / PCM": ["MOV · H.264 / PCM", "MOV · H.264 / PCM"],
  "MP4 · HEVC / AAC": ["MP4 · HEVC / AAC", "MP4 · HEVC / AAC"],
  "TXT · companion file": ["TXT · 随附文件", "TXT · 隨附檔案"],
  "Readable": ["可读取", "可讀取"],
  "Damage": ["损坏", "損壞"],
  "Absent bytes": ["字节缺失", "位元組缺失"],
  "02 / EVIDENCE": ["02 / 证据", "02 / 證據"],
  "STREAM INTEGRITY": ["流完整性", "串流完整性"],
  "FILE BYTES": ["文件字节", "檔案位元組"],
  "Clean full decode": ["全程解码正常", "全程解碼正常"],
  "Container index fault": ["容器索引故障", "容器索引故障"],
  "Video decode errors": ["视频解码错误", "影片解碼錯誤"],
  "Source data absent": ["源数据缺失", "來源資料缺失"],
  "Non-video companion": ["非视频随附文件", "非影片隨附檔案"],
  "The container opens and the intended audio and video streams decode end to end. This establishes readable integrity, not whether the original recording was complete.": ["容器可以打开，预期的音视频流可从头到尾解码。这证明内容可读取，但无法证明原始录制本身完整。", "容器可以開啟，預期的音影片串流可從頭到尾解碼。這證明內容可讀取，但無法證明原始錄製本身完整。"],
  "Encoded media remains readable, but the MP4 index is damaged. A bounded remux can rebuild a playable container without inventing frames.": ["编码媒体仍可读取，但 MP4 索引受损。有限的重新封装可以重建可播放的容器，却不会凭空生成画面。", "已編碼媒體仍可讀取，但 MP4 索引受損。有界的重新封裝可以重建可播放的容器，卻不會憑空生成畫面。"],
  "A short interval contains damaged frames. A compatible encode may retain the readable portion, but the loss must be disclosed and the result independently checked.": ["一小段画面已损坏。兼容编码可能保留可读取的部分，但必须披露损失并独立检查结果。", "一小段畫面已損壞。相容編碼可能保留可讀取的部分，但必須揭露損失並獨立檢查結果。"],
  "The source ends before its expected media is available. The missing bytes cannot be recreated; this example is withheld from the output package.": ["源文件在预期内容结束前就已中断。缺失的字节无法重建；本例不会进入输出包。", "來源檔案在預期內容結束前便已中斷。缺失的位元組無法重建；本例不會納入輸出檔案包。"],
  "Migration can carry a non-video file into the new package and verify its copy byte for byte. Inspect and Repair leave it alone.": ["迁移可以将非视频文件纳入新的输出包，并逐字节验证副本。检查和修复流程不会处理它。", "遷移可以將非影片檔案納入新的輸出檔案包，並逐位元組驗證副本。檢查與修復流程不會處理它。"],
  "START": ["开始", "開始"],
  "PLAYBACK-RELATIVE POSITION": ["相对播放位置", "相對播放位置"],
  "BYTE RANGE": ["字节范围", "位元組範圍"],
  "END": ["结束", "結束"],
  "JOB RESULT": ["任务结果", "工作結果"],
  "PROPOSED ROUTE": ["拟采用的路径", "擬採用的途徑"],
  "Inspect first; publish nothing": ["先检查，不交付任何输出", "先檢查，不交付任何輸出"],
  "Readable throughout": ["全程可读取", "全程可讀取"],
  "Damaged container": ["容器损坏", "容器損壞"],
  "Damaged stream": ["媒体流损坏", "媒體串流損壞"],
  "Incomplete source": ["源文件不完整", "來源檔案不完整"],
  "Software decode inspection": ["软件解码检查", "軟體解碼檢查"],
  "Copied unchanged": ["原样复制", "原樣複製"],
  "Byte-verified companion copy": ["逐字节验证的随附文件副本", "逐位元組驗證的隨附檔案副本"],
  "The synthetic document joins the new package without conversion.": ["这个虚构文档无需转换，就能纳入新的输出包。", "這份虛構文件不需轉換，就能納入新的輸出檔案包。"],
  "Outside this workflow": ["不属于此流程", "不屬於此流程"],
  "No media worker": ["不启动媒体处理器", "不啟動媒體處理器"],
  "Only the migration workflow includes non-video companions.": ["只有迁移流程会纳入非视频随附文件。", "只有遷移流程會納入非影片隨附檔案。"],
  "Withheld for review": ["保留待审", "保留待審"],
  "No verified candidate": ["没有经过验证的候选结果", "沒有經過驗證的候選結果"],
  "Missing source bytes cannot be reconstructed. The original remains untouched and no incomplete output is published.": ["缺失的源文件字节无法重建。原文件保持不变，也不会交付不完整的输出。", "缺失的來源檔案位元組無法重建。原始檔案保持不變，也不會交付不完整的輸出。"],
  "No repair needed": ["无需修复", "無需修復"],
  "Clean source retained": ["保留正常的源文件", "保留正常的來源檔案"],
  "A healthy original does not need a recovered copy unless conversion is explicitly requested.": ["原文件没有损坏，无需制作修复副本；只有明确要求转换时才另行处理。", "原始檔案沒有損壞，不需製作修復副本；只有明確要求轉換時才另行處理。"],
  "Verified recovery": ["修复已验证", "修復已驗證"],
  "Lossless remux → independent decode": ["无损重新封装 → 独立解码", "無損重新封裝 → 獨立解碼"],
  "The container is rebuilt from readable encoded streams; the candidate passes a separate full verification.": ["从可读取的编码流重建容器；候选结果通过单独的完整验证。", "從可讀取的編碼串流重建容器；候選結果通過單獨的完整驗證。"],
  "Verified with losses": ["已验证，有内容损失", "已驗證，有內容損失"],
  "Qualified GPU H.264 / AAC → independent decode": ["经检查的 GPU H.264 / AAC 编码 → 独立解码", "經過檢查的 GPU H.264 / AAC 編碼 → 獨立解碼"],
  "Software H.264 / AAC → independent decode": ["软件 H.264 / AAC → 独立解码", "軟體 H.264 / AAC → 獨立解碼"],
  "A playable result passes verification, with a damaged interval and metadata loss disclosed for review.": ["可播放结果通过验证，同时明确披露损坏时段和元数据损失，供人工检查。", "可播放結果通過驗證，同時明確揭露損壞時段與中繼資料損失，供人工檢查。"],
  "Byte-verified healthy copy": ["逐字节验证的完好副本", "逐位元組驗證的完整副本"],
  "The healthy H.264 MP4 enters the new package without re-encoding under either migration profile.": ["这个完好的 H.264 MP4 在两种迁移配置下都原样纳入输出包，无需重新编码。", "這個完整的 H.264 MP4 在兩種遷移設定下都原樣納入輸出檔案包，不需重新編碼。"],
  "Remux → independent decode": ["重新封装 → 独立解码", "重新封裝 → 獨立解碼"],
  "Readable encoded streams are repackaged and verified before the copy is published.": ["可读取的编码流重新封装并验证后，副本才会纳入输出包。", "可讀取的編碼串流重新封裝並驗證後，副本才會納入輸出檔案包。"],
  "Verified HEVC output": ["HEVC 输出已验证", "HEVC 輸出已驗證"],
  "Qualified GPU HEVC / AAC → independent decode": ["经检查的 GPU HEVC / AAC 编码 → 独立解码", "經過檢查的 GPU HEVC / AAC 編碼 → 獨立解碼"],
  "Software HEVC / AAC → independent decode": ["软件 HEVC / AAC → 独立解码", "軟體 HEVC / AAC → 獨立解碼"],
  "The damaged interval is disclosed. The independently verified playable portion joins the package for human review.": ["损坏时段会明确标出。经过独立验证的可播放部分会纳入输出包，等待人工复核。", "損壞時段會清楚標示。經獨立驗證的可播放部分會納入輸出檔案包，等待人工複核。"],
  "The candidate passes full decode and the selected MP4 output checks before publication.": ["候选结果通过完整解码和所选 MP4 输出检查后，才会纳入输出包。", "候選結果通過完整解碼與所選 MP4 輸出檢查後，才會納入輸出檔案包。"],
  "03 / OPTIONS": ["03 / 选项", "03 / 選項"],
  "Choose the route": ["选择处理路径", "選擇處理途徑"],
  "Migration profile": ["迁移配置", "遷移設定檔"],
  "Keep healthy · MP4 recovery": ["保留完好文件 · 修复 MP4", "保留完整檔案 · 修復 MP4"],
  "Copy clean files; repair only damaged video.": ["复制完好文件；只修复受损视频。", "複製完整檔案；只修復受損影片。"],
  "Selective HEVC MP4": ["选择性 HEVC MP4", "選擇性 HEVC MP4"],
  "Convert eligible video; verify every output.": ["转换符合条件的视频；验证每个输出。", "轉換符合條件的影片；驗證每個輸出。"],
  "Qualified GPU route available": ["可用经检查的 GPU 路径", "可用經過檢查的 GPU 路徑"],
  "Eligible encodes try hardware first.": ["符合条件的编码任务优先尝试硬件。", "符合條件的編碼工作會優先嘗試硬體。"],
  "Eligible encodes use software fallback.": ["符合条件的编码任务改用软件编码。", "符合條件的編碼工作改用軟體編碼。"],
  "Inspection uses software decoding. GPU routing applies to repair and migration.": ["检查使用软件解码。GPU 路径适用于修复和迁移。", "檢查使用軟體解碼。GPU 途徑適用於修復與遷移。"],
  "Mask sample names": ["隐藏样本名称", "隱藏樣本名稱"],
  "On · show neutral item numbers.": ["开启 · 显示中性编号。", "開啟 · 顯示中性編號。"],
  "Off · show invented sample names.": ["关闭 · 显示虚构的样本名称。", "關閉 · 顯示虛構的樣本名稱。"],
  "04 / ACTIVITY": ["04 / 活动", "04 / 活動"],
  "Sample job": ["样本任务", "範例工作"],
  "Sample job stages": ["样本任务阶段", "範例工作階段"],
  "READY": ["就绪", "就緒"],
  "RUNNING": ["运行中", "執行中"],
  "COMPLETE": ["已完成", "已完成"],
  "Discover": ["查找", "尋找"],
  "Classify five invented items without opening a visitor file.": ["给五个虚构文件分类，不会打开访客的文件。", "將五個虛構檔案分類，不會開啟訪客的檔案。"],
  "Model container and full software-decode findings.": ["模拟容器检查和完整软件解码结果。", "模擬容器檢查與完整軟體解碼結果。"],
  "Plan": ["规划", "規劃"],
  "Choose eligible copy, remux or encode routes.": ["选择符合条件的复制、重新封装或编码路径。", "選擇符合條件的複製、重新封裝或編碼途徑。"],
  "Verify": ["验证", "驗證"],
  "Check each proposed output before publication.": ["交付前检查每个候选输出。", "交付前檢查每個候選輸出。"],
  "Review": ["复核", "複核"],
  "Show published, unchanged and withheld outcomes.": ["展示可交付、保持原样和暂缓处理的结果。", "展示可交付、維持原樣和暫緩處理的結果。"],
  "Run another pass": ["再次运行", "再次執行"],
  "Working…": ["处理中…", "處理中…"],
  "Run sample job": ["运行样本任务", "執行樣本工作"],
  "Ready to simulate. No real media is touched.": ["准备模拟；不会触碰真实媒体。", "準備模擬；不會接觸真實媒體。"],
  "05 / REVIEW": ["05 / 复核", "05 / 複核"],
  "Inspection findings": ["检查结果", "檢查結果"],
  "Verified package report": ["已验证输出报告", "已驗證輸出報告"],
  "5 classified": ["已分类 5 项", "已分類 5 項"],
  "{0} published · {1} withheld": ["可交付 {0} 项 · 暂缓 {1} 项", "可交付 {0} 項 · 暫緩 {1} 項"],
  "This is an explanatory simulation. Verification shown here is a modeled decision, not proof from a processed file. Originals remain untouched.": ["这只是流程演示。页面上的验证结论是模拟出来的，并非处理真实文件所得；原始文件始终不变。", "這只是流程示範。頁面上的驗證結論是模擬結果，並非處理真實檔案所得；原始檔案始終不變。"],
} satisfies ProjectCopyTable;
