// One generated image per subject, shared by desktop, menu and document views.
// Size belongs to the containing control; it never selects alternate artwork.
export const SYSTEM7_ICONS = {
  profile: "/system7-icons/profile.png",
  computer: "/system7-icons/computer.png",
  briefcase: "/system7-icons/briefcase.png",
  folder: "/system7-icons/folder.png",
  document: "/system7-icons/document.png",
  controls: "/system7-icons/controls.png",
  university: "/system7-icons/university.png",
  network: "/system7-icons/network.png",
  photos: "/system7-icons/photos.png",
  runner: "/system7-icons/runner.png",
  game: "/system7-icons/game.png",
  accessories: "/system7-icons/accessories.png",
  note: "/system7-icons/note.png",
  sketch: "/system7-icons/sketch.png",
  tasks: "/system7-icons/tasks.png",
  clock: "/system7-icons/clock.png",
  calendar: "/system7-icons/calendar.png",
  calculator: "/system7-icons/calculator.png",
  converter: "/system7-icons/converter.png",
  palette: "/system7-icons/palette.png",
  orbital: "/system7-icons/orbital.png",
  pdf: "/system7-icons/pdf.png",
  mail: "/system7-icons/mail.png",
  secret: "/system7-icons/secret.png",
  minefield: "/system7-icons/minefield.png",
  snake: "/system7-icons/snake.png",
  brickbreaker: "/system7-icons/brickbreaker.png",
  cards: "/system7-icons/cards.png",
  puzzle: "/system7-icons/puzzle.png",
  word: "/system7-icons/word.png",
  spectrum: "/system7-icons/spectrum.png",
  microscope: "/system7-icons/microscope.png",
  finance: "/system7-icons/finance.png",
  chart: "/system7-icons/chart.png",
  molecule: "/system7-icons/molecule.png",
  shield: "/system7-icons/shield.png",
  book: "/system7-icons/book.png",
  mri: "/system7-icons/mri.png",
  flow: "/system7-icons/flow.png",
  coverd: "/system7-icons/coverd.png",
  videomate: "/system7-icons/videomate.png",
  finder: "/system7-icons/finder.png",
} as const;

export type System7IconKind = keyof typeof SYSTEM7_ICONS;
