import type { ProjectCopyTable } from "@/lib/projectCopy";

/** Profile copy is kept beside its evidence-backed records, away from legacy text. */
export const profileCopy = {
  "Career records from the CV, connected to public work and original showcases.": ["简历中的经历记录，关联公开作品与原始展示资料。", "履歷中的經歷紀錄，連結公開作品與原始展示資料。"],
  "Related subject context": ["相关学科背景", "相關學科背景"],
  "Record sources": ["记录来源", "紀錄來源"],
  "Sources": ["来源", "來源"],
  "Project evidence": ["项目证据", "專案證據"],
  "Linked experience and education": ["关联经历与教育", "關聯經歷與教育"],
  "Experience & education": ["经历与教育", "經歷與教育"],
  "Open a capability to see the work, experience and sources behind it.": ["展开一项能力，查看其对应的作品、经历与来源。", "展開一項能力，查看其對應的作品、經歷與來源。"],
  "Degree subjects": ["学位课程", "學位課程"],
  "Alongside the degree": ["学位期间的经历", "學位期間的經歷"],
  "Explore language-learning work →": ["探索语言学习作品 →", "探索語言學習作品 →"],
  "Document library": ["文档库", "文件庫"],
  "Open related project": ["打开相关项目", "開啟相關專案"],
  "Applied AI CV": ["应用 AI 简历", "應用 AI 履歷"],
  "GROWMAT external showcase": ["GROWMAT 对外展示", "GROWMAT 對外展示"],
  "2025 ISMS conference record": ["2025 ISMS 会议记录", "2025 ISMS 會議紀錄"],
  "RUN/HACK field journal": ["RUN/HACK 现场日志", "RUN/HACK 現場日誌"],
  "Studied protein–membrane interactions in silico and used the analysis to refine experimental design. The related GROMACS environment and topology-preparation project was completed later, in 2025.": ["使用计算方法研究蛋白质与膜的相互作用，并用分析结果改进实验设计。关联的 GROMACS 环境配置与拓扑准备项目在之后的 2025 年完成。", "使用計算方法研究蛋白質與膜的交互作用，並用分析結果改進實驗設計。相關的 GROMACS 環境設定與拓樸準備專案於之後的 2025 年完成。"],
  "MSc AI Applications & Innovation": ["人工智能应用与创新理学硕士", "人工智慧應用與創新理學碩士"],
  "Imperial College London": ["伦敦帝国理工学院", "倫敦帝國學院"],
  "Predicted Distinction": ["预计优等成绩", "預計優等成績"],
  "BSc Chemistry with Biomedicine": ["化学与生物医学理学学士", "化學與生物醫學理學學士"],
  "King’s College London": ["伦敦国王学院", "倫敦國王學院"],
  "King’s Research Experience Award": ["国王学院研究经历奖", "國王學院研究經歷獎"],
  "Associate of King’s College London (AKC)": ["伦敦国王学院院士资格（AKC）", "倫敦國王學院院士資格（AKC）"],
  "First-Class Honours": ["一等荣誉学位", "一等榮譽學位"],
  "Deep Learning": ["深度学习", "深度學習"],
  "AI Safety": ["人工智能安全", "人工智慧安全"],
  "Innovation Management": ["创新管理", "創新管理"],
  "Machine Learning in Medical Imaging": ["医学影像中的机器学习", "醫學影像中的機器學習"],
  "Machine Learning in Climate Change": ["气候变化中的机器学习", "氣候變遷中的機器學習"],
  "Computational Chemistry": ["计算化学", "計算化學"],
  "Molecular Biology": ["分子生物学", "分子生物學"],
  "Chemical Biology": ["化学生物学", "化學生物學"],
  "Organic Chemistry": ["有机化学", "有機化學"],
  "Applied AI study connecting model development, safety and the practical work of introducing new technology. The linked archive includes medical imaging, scientific machine learning, evaluation and venture-design projects.": ["应用 AI 学习连接模型开发、安全和引入新技术的实际工作。关联档案包含医学影像、科学机器学习、评估与创业设计项目。", "應用 AI 學習連結模型開發、安全與導入新技術的實務工作。相關檔案包含醫學影像、科學機器學習、評估與創業設計專案。"],
  "Degree result recorded in the CV as Predicted Distinction.": ["简历将学位成绩记为预计优等。", "履歷將學位成績記為預計優等。"],
  "Research and coursework span microrobot perception, MRI reconstruction, fluid-flow surrogates and decisions under uncertainty.": ["研究与课程作品涵盖微型机器人感知、MRI 重建、流体代理模型与不确定性下的决策。", "研究與課程作品涵蓋微型機器人感知、MRI 重建、流體代理模型與不確定性下的決策。"],
  "A chemistry degree with biomedicine and a professional placement in Pfizer Analytical R&D. Scientific-computing coursework grew into experiments in sampling, molecular dynamics, polymer models and quantum chemistry.": ["化学与生物医学学位包括辉瑞分析研发部门的专业实习。科学计算课程进一步发展为采样、分子动力学、聚合物模型与量子化学实验。", "化學與生物醫學學位包括輝瑞分析研發部門的專業實習。科學計算課程進一步發展為取樣、分子動力學、聚合物模型與量子化學實驗。"],
  "Professional placement at Pfizer, followed by part-time GROWMAT product ownership.": ["在辉瑞完成专业实习，随后兼职负责 GROWMAT 产品。", "於輝瑞完成專業實習，隨後兼職負責 GROWMAT 產品。"],
  "King’s Research Experience Award and the Associate of King’s College London programme.": ["获得国王学院研究经历奖，并完成伦敦国王学院院士课程。", "獲得國王學院研究經歷獎，並完成倫敦國王學院院士課程。"],
  "Undergraduate research in rotational spectroscopy, followed by a protein–membrane research project.": ["本科研究涵盖转动光谱学，随后开展蛋白质与膜的研究项目。", "大學研究涵蓋轉動光譜學，隨後開展蛋白質與膜的研究專案。"],
  "Application evidence, specialist evaluation and human decisions connected in one product.": ["在同一产品中连接申请证据、专业评估与人工决策。", "於同一產品中連結申請證據、專業評估與人工決策。"],
  "Interfaces, services and data models shaped around an inspectable workflow.": ["围绕可检查的工作流程设计界面、服务与数据模型。", "圍繞可檢查的工作流程設計介面、服務與資料模型。"],
  "Baselines, provenance and failure analysis that explain what a model can support.": ["通过基线、来源与失败分析说明模型能支持什么。", "透過基準、來源與失敗分析說明模型能支持什麼。"],
  "Connected services, repeatable environments and explicit recovery limits.": ["连接服务、可重复环境与明确的恢复限制。", "串接服務、可重複環境與明確的復原限制。"],
  "Computational models grounded in chemistry, experiment design and numerical checks.": ["计算模型以化学、实验设计与数值检查为基础。", "計算模型以化學、實驗設計與數值檢查為基礎。"],
  "Discovery, product ownership and teaching that help people use technical work.": ["通过需求探索、产品负责与教学，帮助人们使用技术成果。", "透過需求探索、產品負責與教學，協助人們使用技術成果。"],
  "Multi-agent application review": ["多智能体申请审查", "多代理申請審查"],
  "Voice interviews & evidence gathering": ["语音面试与证据收集", "語音面試與證據蒐集"],
  "Human review & responsible AI": ["人工审查与负责任的 AI", "人工審查與負責任的 AI"],
  "TypeScript, React & product interfaces": ["TypeScript、React 与产品界面", "TypeScript、React 與產品介面"],
  "Python services & APIs": ["Python 服务与 API", "Python 服務與 API"],
  "SQL, PostgreSQL & data modelling": ["SQL、PostgreSQL 与数据建模", "SQL、PostgreSQL 與資料建模"],
  "Retrieval, document intelligence & ranking": ["检索、文档智能与排序", "檢索、文件智慧與排序"],
  "Time-aware validation & error analysis": ["时间感知验证与误差分析", "時間感知驗證與誤差分析"],
  "Causal & off-policy evaluation": ["因果与离策略评估", "因果與離策略評估"],
  "Docker, Linux & Proxmox": ["Docker、Linux 与 Proxmox", "Docker、Linux 與 Proxmox"],
  "Backups, reliability & recovery": ["备份、可靠性与恢复", "備份、可靠性與復原"],
  "Accelerator & scientific environments": ["加速器与科学计算环境", "加速器與科學計算環境"],
  "Julia, MATLAB & scientific Python": ["Julia、MATLAB 与科学 Python", "Julia、MATLAB 與科學 Python"],
  "Scientific machine learning": ["科学机器学习", "科學機器學習"],
  "Spectroscopy & molecular simulation": ["光谱学与分子模拟", "光譜學與分子模擬"],
  "Customer discovery & product ownership": ["客户需求探索与产品负责", "客戶需求探索與產品負責"],
  "Teaching, curriculum design & mentoring": ["教学、课程设计与指导", "教學、課程設計與指導"],
  "Decision support under pressure": ["压力下的决策支持", "壓力下的決策支援"],
  "COVERD reviews applications across specialist dimensions and retains supporting evidence for recruiter inspection.": ["COVERD 从专业维度审查申请，并保留支持证据供招聘人员检查。", "COVERD 從專業維度審查申請，並保留支持證據供招募人員檢查。"],
  "Three voice-interview architectures were tested across 20 candidate interviews by April 2026; the current product uses optional interviews to fill application evidence gaps.": ["截至 2026 年 4 月，在 20 次候选人面试中测试了三种语音面试架构；目前的产品通过可选面试填补申请证据缺口。", "截至 2026 年 4 月，在 20 次候選人面試中測試了三種語音面試架構；目前的產品透過可選面試填補申請證據缺口。"],
  "Recruiters retain the final COVERD decision. Research and public decision experiments also examine uncertainty, oversight and when a model should defer.": ["招聘人员保留 COVERD 的最终决策权。研究与公开决策实验也探讨不确定性、监督，以及模型何时应交由人工处理。", "招募人員保留 COVERD 的最終決策權。研究與公開決策實驗也探討不確定性、監督，以及模型何時應交由人工處理。"],
  "GROWMAT connects a Next.js editing interface with workload calculations and governed data; independent applications explore local, inspectable state.": ["GROWMAT 将 Next.js 编辑界面与工作量计算和受控数据连接；独立应用探索本地、可检查的状态。", "GROWMAT 將 Next.js 編輯介面與工作量計算及受控資料串接；獨立應用程式探索本機、可檢查的狀態。"],
  "Python powers applied-AI services and VideoMate’s native video inspection and migration workflow. The public insurance project documents a FastAPI-based prototype.": ["Python 支持应用 AI 服务与 VideoMate 原生视频检查和迁移流程。公开保险项目记录了基于 FastAPI 的原型。", "Python 支援應用 AI 服務與 VideoMate 原生影片檢查和移轉流程。公開保險專案記錄了基於 FastAPI 的原型。"],
  "The GROWMAT showcase documents ten source datasets feeding eleven governed tables, scheduled calculations and capacity views.": ["GROWMAT 展示资料记录了十个源数据集输入十一个受控表格，以及定时计算和产能视图。", "GROWMAT 展示資料記錄了十個來源資料集輸入十一個受控資料表，以及排程計算與產能檢視。"],
  "The public insurance project explains temporal market ranking, historical placement context and wording analysis with clause citations. Its interactive examples use fictional inputs.": ["公开保险项目解释了时间市场排序、历史承保背景与附有条款引用的措辞分析。交互示例使用虚构输入。", "公開保險專案解釋了時間市場排序、歷史承保背景與附有條款引用的措辭分析。互動範例使用虛構輸入。"],
  "Insurance ranking uses information available at the decision time. The scientific archive inspects calibration, uncertainty rankings and reconstruction errors.": ["保险排序使用决策时可获得的信息。科学档案检查校准、不确定性排序与重建误差。", "保險排序使用決策時可取得的資訊。科學檔案檢查校準、不確定性排序與重建誤差。"],
  "The off-policy laboratory compares causal assumptions, propensity weighting and evaluation methods through reproducible experiments.": ["离策略实验室通过可复现实验比较因果假设、倾向加权与评估方法。", "離策略實驗室透過可重現實驗比較因果假設、傾向加權與評估方法。"],
  "The private home lab connects local AI, storage and automation; its public audit follows six declared Docker services and their dependencies.": ["私人家庭实验室连接本地 AI、存储与自动化；公开审计追踪六项声明的 Docker 服务及其依赖。", "私人家庭實驗室串接本機 AI、儲存與自動化；公開稽核追蹤六項聲明的 Docker 服務及其相依關係。"],
  "GROWMAT documents scheduled backups and retention. The home-lab audit exposes restore-testing and recovery-evidence gaps rather than treating a backup schedule as proof of recovery.": ["GROWMAT 记录了定时备份与保留策略。家庭实验室审计指出恢复测试与恢复证据的缺口，备份计划并不代表已经验证恢复。", "GROWMAT 記錄了排程備份與保留策略。家庭實驗室稽核指出復原測試與復原證據的缺口，備份計畫並不代表已經驗證復原。"],
  "The environment planner checks accelerator compatibility. GROMACS work covers GPU-capable container setup and topology preprocessing, with its scope recorded separately from earlier research.": ["环境规划器检查加速器兼容性。GROMACS 工作涵盖 GPU 容器配置与拓扑预处理，其范围与此前的研究分开记录。", "環境規劃器檢查加速器相容性。GROMACS 工作涵蓋 GPU 容器設定與拓樸前處理，其範圍與先前的研究分開記錄。"],
  "The archive includes a Julia stochastic stock-market simulator, a MATLAB spectroscopy plotting utility and computational-chemistry notebooks and extensions.": ["档案包含 Julia 随机股市模拟器、MATLAB 光谱绘图工具，以及计算化学笔记本与扩展。", "檔案包含 Julia 隨機股市模擬器、MATLAB 光譜繪圖工具，以及計算化學筆記本與擴充。"],
  "MSc projects explore microrobot perception, MRI reconstruction and neural fluid-flow surrogates, with public explanations of model architecture and evaluation limits.": ["硕士项目探索微型机器人感知、MRI 重建与神经流体代理模型，并公开解释模型架构和评估限制。", "碩士專案探索微型機器人感知、MRI 重建與神經流體代理模型，並公開解釋模型架構和評估限制。"],
  "Undergraduate research included rotational-spectroscopy analysis and protein–membrane interactions in silico. The 2025 ISMS record names Samuel as a co-author on the molecular-recognition work.": ["本科研究涵盖转动光谱分析与蛋白质和膜相互作用的计算研究。2025 年 ISMS 记录将 Samuel 列为分子识别研究的共同作者。", "大學研究涵蓋轉動光譜分析與蛋白質和膜交互作用的計算研究。2025 年 ISMS 紀錄將 Samuel 列為分子辨識研究的共同作者。"],
  "COVERD discovery involved four design partners and a product pivot. GROWMAT work combined roadmap ownership, stakeholder adoption and delivery in regulated R&D.": ["COVERD 的需求探索涉及四个设计合作伙伴与一次产品转型。GROWMAT 工作结合路线图负责、利益相关者采用与受监管研发中的交付。", "COVERD 的需求探索涉及四個設計合作夥伴與一次產品轉型。GROWMAT 工作結合路線圖負責、利害關係人採用與受監管研發中的交付。"],
  "Designed and delivered 20+ programming, data-analysis and introductory ML sessions for 80+ chemistry students, and organised a careers panel for 100+ students. The linked chemistry archive supplies related subject context.": ["为 80 多名化学学生设计并开展 20 多场编程、数据分析与机器学习入门课程，并为 100 多名学生组织职业座谈会。关联的化学档案提供相关学科背景。", "為 80 多名化學學生設計並開展 20 多場程式設計、資料分析與機器學習入門課程，並為 100 多名學生組織職涯座談會。相關化學檔案提供相關學科背景。"],
  "National service combined public-data workflow automation during COVID-19 with time-critical support for senior leaders. Operational and personnel details remain protected.": ["国民服役期间，结合 COVID-19 公共数据工作流程自动化与对高级领导的紧急支持。行动与人员详情仍受保护。", "國民服役期間，結合 COVID-19 公共資料工作流程自動化與對高階領導的緊急支援。行動與人員詳情仍受保護。"],
  "GROWMAT — External Showcase": ["GROWMAT — 对外展示", "GROWMAT — 對外展示"],
  "Enterprise product · English PDF": ["企业产品 · 英文 PDF", "企業產品 · 英文 PDF"],
  "The original external showcase explains GROWMAT’s seven-component architecture, governed data, workload modelling and capacity views.": ["原始对外展示解释 GROWMAT 的七组件架构、受控数据、工作量建模与产能视图。", "原始對外展示解釋 GROWMAT 的七元件架構、受控資料、工作量建模與產能檢視。"],
  "A structured syllabus for reinforcement-learning study, connected to the archive’s learning atlas and browser experiments.": ["结构化的强化学习课程大纲，关联档案中的学习图谱与浏览器实验。", "結構化的強化學習課程大綱，連結檔案中的學習圖譜與瀏覽器實驗。"],
  "Italian Practice Workbook": ["意大利语练习册", "義大利語練習冊"],
  "Bilingual Italian Reading Workbook": ["意大利语双语阅读册", "義大利語雙語閱讀冊"],
  "Language learning · English / Italian PDF": ["语言学习 · 英语 / 意大利语 PDF", "語言學習 · 英語 / 義大利語 PDF"],
  "Practice material from the Parliamo language-learning project, with exercises that complement the interactive learning studio.": ["Parliamo 语言学习项目的练习资料，与交互学习工作室配套使用。", "Parliamo 語言學習專案的練習資料，與互動學習工作室搭配使用。"],
  "Bilingual reading material from Parliamo, collected here alongside its practice workbook and interactive learning tools.": ["Parliamo 的双语阅读资料，在此与练习册及交互学习工具一起收录。", "Parliamo 的雙語閱讀資料，在此與練習冊及互動學習工具一同收錄。"],
  "The CV records experience, degree subjects, awards and languages; the profile windows connect those records to public work.": ["简历记录经历、学位课程、奖项与语言；个人资料窗口将这些记录关联到公开作品。", "履歷記錄經歷、學位課程、獎項與語言；個人資料視窗將這些紀錄連結至公開作品。"],
} satisfies ProjectCopyTable;
