import type { Project, ProjectArea } from "./projects";
import type { ProjectOrigin } from "./projectOrigins";

export type KnowledgeKind = "topic" | "method" | "project" | "experience";
export type KnowledgeNode = {
  id: string; kind: KnowledgeKind; label: string; shortLabel: string;
  description: string; colour: string; topic: string;
  slug?: string; section?: "experience" | "education"; anchor?: string; period?: string;
};
export type KnowledgeEdge = {
  id: string; source: string; target: string;
  relation: "explores" | "uses" | "part-of" | "developed-in" | "related-context";
  explanation: string;
};
export type KnowledgeGraphData = { version: 1; nodes: KnowledgeNode[]; edges: KnowledgeEdge[] };
type Topic = { id: string; label: string; shortLabel: string; description: string; colour: string };
type Method = { id: string; label: string; topic: string; description: string };

export const knowledgeTopics: Topic[] = [
  { id: "reinforcement-learning", label: "Reinforcement learning", shortLabel: "Reinforcement learning", colour: "#126887", description: "How agents learn through action, feedback and repeated decisions. Follow value functions, exploration, policy evaluation and language-model post-training." },
  { id: "scientific-ml", label: "Scientific machine learning", shortLabel: "Scientific ML", colour: "#67418c", description: "Learning the behaviour of physical systems: fluid fields, medical images and microrobots. Explore model structure alongside the experiments used to assess it." },
  { id: "chemistry", label: "Chemistry & molecular science", shortLabel: "Chemistry", colour: "#88590b", description: "From molecular spectra and phase equilibria to quantum orbitals. Follow the measurements, calculations and tools behind a chemical interpretation." },
  { id: "decisions", label: "Decision systems", shortLabel: "Decision systems", colour: "#27694d", description: "Models that support a consequential choice: allocating insurance leads, deferring uncertain cases, estimating effects and reviewing operational evidence." },
  { id: "products", label: "Products & tools", shortLabel: "Products & tools", colour: "#963758", description: "Software people use to organise work, learn, plan and create. Trace a working interaction back to its data, rules and product context." },
  { id: "infrastructure", label: "Computing & infrastructure", shortLabel: "Computing & systems", colour: "#3e5482", description: "The environments and services that make experiments and products usable: accelerators, containers, local storage and recovery procedures." },
  { id: "data-science", label: "Data & model evaluation", shortLabel: "Data & evaluation", colour: "#76630b", description: "How datasets become evidence. Inspect split design, leakage, regularisation, calibration, error measures and the assumptions behind a reported result." },
  { id: "human-systems", label: "People, organisations & AI", shortLabel: "People & organisations", colour: "#9b4824", description: "The organisational side of technical work: research ethics, innovation, capacity planning, product ownership and human review." },
];

export const knowledgeMethods: Method[] = [
  { id: "value-and-policy", label: "Values & policies", topic: "reinforcement-learning", description: "Estimate future return, choose actions and inspect the update rule that changes an agent’s behaviour." },
  { id: "bandits", label: "Exploration & bandits", topic: "reinforcement-learning", description: "Allocate repeated decisions between gathering information and using the evidence already available." },
  { id: "language-models", label: "Language-model training", topic: "reinforcement-learning", description: "Inspect supervised adaptation, low-rank updates, preference objectives and the answers generated by a trained model." },
  { id: "language-applications", label: "Language-model applications", topic: "decisions", description: "Use language models to interpret text, gather evidence and support a person’s decision." },
  { id: "language-processing", label: "Text processing & matching", topic: "products", description: "Extract terms, compare documents and connect relevant language with explicit rules." },
  { id: "fourier-operators", label: "Fourier operators", topic: "scientific-ml", description: "Transform a field into frequency components, learn spectral interactions and reconstruct a prediction in physical space." },
  { id: "graph-networks", label: "Graph message passing", topic: "scientific-ml", description: "Compute local messages between connected nodes and aggregate them to update a field on a mesh." },
  { id: "inverse-problems", label: "Imaging & inverse problems", topic: "scientific-ml", description: "Recover an image or latent physical property from indirect, incomplete or noisy measurements." },
  { id: "robotics", label: "Robotics & perception", topic: "scientific-ml", description: "Connect sensed observations, geometric state and a physical system’s motion." },
  { id: "uncertainty", label: "Uncertainty & calibration", topic: "data-science", description: "Compare confidence with observed outcomes and study how uncertainty changes a decision." },
  { id: "evaluation", label: "Splits, metrics & leakage", topic: "data-science", description: "Track which observations trained a model, which evaluated it and what each metric actually measures." },
  { id: "regularisation", label: "Regularisation & optimisation", topic: "data-science", description: "Control a model’s fit through penalties, optimisation choices and the trade-off between training error and generalisation." },
  { id: "causal-inference", label: "Causal & counterfactual reasoning", topic: "decisions", description: "Separate associations from effects and evaluate alternative decisions using explicitly stated assumptions." },
  { id: "human-review", label: "Human review & deferral", topic: "decisions", description: "Route evidence to a person, retain the basis of a recommendation and decide when a model should defer." },
  { id: "spectroscopy", label: "Spectroscopy", topic: "chemistry", description: "Connect measured frequencies and intensities to molecular structure through prediction, matching and visual analysis." },
  { id: "thermodynamics", label: "Thermodynamics", topic: "chemistry", description: "Calculate bulk properties and phase equilibria from molecular models and measured material properties." },
  { id: "quantum", label: "Quantum & molecular simulation", topic: "chemistry", description: "Explore wavefunctions, molecular motion and numerical experiments that connect microscopic structure to observable behaviour." },
  { id: "local-first", label: "Local data & persistence", topic: "products", description: "Keep a useful record across interactions, reconcile overlapping inputs and make the resulting state inspectable." },
  { id: "scheduling", label: "Scheduling & allocation", topic: "products", description: "Allocate people, time or capacity under explicit constraints, then examine conflicts and overrides." },
  { id: "learning-tools", label: "Learning tools", topic: "products", description: "Turn a curriculum or technical idea into something a learner can practise, inspect and revisit." },
  { id: "recovery", label: "Infrastructure & recovery", topic: "infrastructure", description: "Trace service dependencies, accelerator environments, backups and recovery steps through concrete failure cases." },
  { id: "innovation", label: "Innovation & venture design", topic: "human-systems", description: "Connect a proposed product to its evidence, organisational setting, adoption path and resource needs." },
  { id: "governance", label: "Ethics & governance", topic: "human-systems", description: "Examine affected people, responsibilities, uncertainty and oversight when a technical system is introduced." },
];

/** Concepts are curated relationships. Shared access labels and project status
 * have no bearing on semantic links. A new project can declare its concepts in
 * projects.ts; an area fallback keeps an unfinished record discoverable.
 */
export const projectConcepts: Record<string, string[]> = {
  "orbital-lab": ["chemistry", "quantum", "learning-tools"],
  "desk-note-pad": ["products", "local-first"], "desk-sketch-pad": ["products", "local-first"],
  "desk-quick-list": ["products", "local-first"], "desk-focus-clock": ["products", "local-first"],
  "desk-pocket-calendar": ["products", "scheduling", "local-first"], "desk-calculator": ["products", "learning-tools"],
  "desk-unit-converter": ["products", "learning-tools"], "desk-colour-studio": ["products", "learning-tools"],
  "coverd-ai": ["human-systems", "products", "human-review", "language-applications", "governance"],
  "growmat": ["products", "human-systems", "scheduling"],
  "insurance-lead-matching": ["decisions", "human-review", "evaluation", "language-applications"],
  "cv-keyword-automator": ["products", "human-review", "language-processing"],
  "ocean-depths-finance": ["products", "local-first", "evaluation"],
  "coverd-yasa": ["products", "scheduling", "recovery"],
  "parliamo-italian-learning": ["products", "learning-tools", "local-first"],
  "course-recommender-audit": ["data-science", "learning-tools", "evaluation"],
  "study-rl": ["reinforcement-learning", "value-and-policy", "bandits", "language-models"],
  "sequential-decisions-lab": ["reinforcement-learning", "bandits", "evaluation"],
  "microrobot-vision": ["scientific-ml", "robotics", "inverse-problems", "evaluation"],
  "trustworthy-mri-reconstruction": ["scientific-ml", "inverse-problems", "uncertainty", "evaluation"],
  "neural-cfd-surrogates": ["scientific-ml", "fourier-operators", "graph-networks", "evaluation"],
  "air-quality-sensor-optimisation": ["data-science", "evaluation", "regularisation"],
  "cost-sensitive-cyber-detection": ["data-science", "evaluation", "human-review"],
  "regularisation-lab": ["data-science", "regularisation"],
  "safety-critical-ai": ["data-science", "uncertainty", "evaluation"],
  "safe-learning-to-defer": ["decisions", "human-review", "uncertainty"],
  "causal-ope-lab": ["decisions", "causal-inference", "bandits"],
  "innovation-models-reflection": ["human-systems", "innovation"],
  "ai-venture-reasoning": ["human-systems", "innovation", "evaluation"],
  "pc-saft-thermodynamics": ["chemistry", "thermodynamics"],
  "drug-solubility": ["chemistry", "thermodynamics"],
  "molecular-recognition": ["chemistry", "spectroscopy"],
  "cprot-spectroscopy-plotter": ["chemistry", "spectroscopy", "products"],
  "deep-learning-environment-resolver": ["infrastructure", "recovery"],
  "gromacs-hpc": ["infrastructure", "quantum", "recovery"],
  "home-automation-stack": ["infrastructure", "recovery", "local-first"],
  "stock-market-engine": ["data-science", "evaluation"],
  "covid-decision-support": ["decisions", "human-systems", "human-review"],
  "coding-series": ["chemistry", "quantum", "regularisation"],
};

const areaFallback: Record<ProjectArea, string> = { Products: "products", "Applied AI": "decisions", "Machine Learning": "data-science", Research: "scientific-ml", Systems: "infrastructure", Education: "products" };

export function buildKnowledgeGraph(catalogue: Project[], origins: ProjectOrigin[]): KnowledgeGraphData {
  const nodes: KnowledgeNode[] = knowledgeTopics.map((topic) => ({ ...topic, id: `topic:${topic.id}`, kind: "topic", topic: topic.id }));
  const edges: KnowledgeEdge[] = [];
  const edgeIds = new Set<string>();
  const topicMap = new Map(knowledgeTopics.map((topic) => [topic.id, topic]));
  const methodMap = new Map(knowledgeMethods.map((method) => [method.id, method]));
  const addEdge = (source: string, target: string, relation: KnowledgeEdge["relation"], explanation: string) => {
    const id = `${source}~${relation}~${target}`;
    if (!edgeIds.has(id)) { edgeIds.add(id); edges.push({ id, source, target, relation, explanation }); }
  };
  for (const method of knowledgeMethods) {
    nodes.push({ ...method, id: `method:${method.id}`, kind: "method", shortLabel: method.label, colour: topicMap.get(method.topic)!.colour });
    addEdge(`method:${method.id}`, `topic:${method.topic}`, "part-of", `${method.label} is a route into ${topicMap.get(method.topic)!.label.toLowerCase()}.`);
  }
  for (const project of catalogue) {
    const concepts = project.concepts ?? projectConcepts[project.slug] ?? [areaFallback[project.area]];
    const topic = topicMap.has(concepts[0]) ? concepts[0] : methodMap.get(concepts[0])?.topic ?? areaFallback[project.area];
    const id = `project:${project.slug}`;
    nodes.push({ id, kind: "project", label: project.title, shortLabel: project.shortTitle ?? project.title, description: project.summary, slug: project.slug, period: project.year, topic, colour: topicMap.get(topic)!.colour });
    for (const concept of concepts) {
      if (topicMap.has(concept)) addEdge(id, `topic:${concept}`, "explores", `${project.title} explores ${topicMap.get(concept)!.label.toLowerCase()}.`);
      else if (methodMap.has(concept)) {
        const method = methodMap.get(concept)!;
        addEdge(id, `method:${concept}`, "uses", `${project.title} includes ${method.label.toLowerCase()}. ${method.description}`);
        addEdge(id, `topic:${method.topic}`, "explores", `${project.title} connects to ${topicMap.get(method.topic)!.label.toLowerCase()} through ${method.label.toLowerCase()}.`);
      } else throw new Error(`Unknown knowledge concept ${concept} on ${project.slug}`);
    }
  }
  for (const origin of origins) {
    const linked = nodes.filter((node) => node.slug && origin.projects.includes(node.slug));
    if (!linked.length) continue;
    const topic = linked[0].topic;
    const id = `experience:${origin.id}`;
    nodes.push({ id, kind: "experience", label: origin.label, shortLabel: origin.label.split(" · ")[0], description: origin.context, section: origin.section, anchor: origin.id, period: origin.period, topic, colour: "#303030" });
    for (const project of linked) {
      const related = !!project.slug && !!origin.relatedProjects?.includes(project.slug);
      addEdge(project.id, id, related ? "related-context" : "developed-in", origin.context);
    }
  }
  return { version: 1, nodes, edges };
}

export type KnowledgeConnection = { edge: KnowledgeEdge; node: KnowledgeNode };

/** Read-only graph index. Build once per catalogue, then traverse a node's
 * connections in O(degree). Rendering remains capped independently of size. */
export class KnowledgeGraphIndex {
  readonly nodes: ReadonlyMap<string, KnowledgeNode>;
  private readonly connections = new Map<string, KnowledgeConnection[]>();

  constructor(graph: KnowledgeGraphData) {
    this.nodes = new Map(graph.nodes.map((node) => [node.id, node]));
    for (const edge of graph.edges) {
      const source = this.nodes.get(edge.source), target = this.nodes.get(edge.target);
      if (!source || !target) throw new Error(`Broken graph connection: ${edge.id}`);
      for (const [id, node] of [[source.id, target], [target.id, source]] as const) {
        const entries = this.connections.get(id) ?? [];
        entries.push({ edge, node }); this.connections.set(id, entries);
      }
    }
  }

  neighbours(id: string): readonly KnowledgeConnection[] {
    return this.connections.get(id) ?? [];
  }
}

export function graphNeighbours(graph: KnowledgeGraphData, id: string) {
  return new KnowledgeGraphIndex(graph).neighbours(id);
}

export function graphNodeHref(node: KnowledgeNode, localeSlug: string) {
  return node.kind === "experience"
    ? `/${localeSlug}/${node.section}#${node.anchor}`
    : `/${localeSlug}/projects?view=map&node=${encodeURIComponent(node.id)}`;
}
